### PR TITLE
LLM-Assistant improvement

### PR DESCRIPTION
**Pull request by dhrsal123**
Ive improved the code, is faster(thanks to the gpu support) and now the weather function works, also the date is taken using the datetime library so it should be the date the user has

### CODE REVIEW

**Comment by dhrsal123** [comment]
Comment out line #289(on main.py), i was doing some testing and forgot to delete it

**Comment by dhrsal123** [comment]
remove line 15 on README.md, as theres no support(yet) for custom System prompt

**Review by Rivridis — APPROVED** [review]
Yup, LGTM. Merging PR, but will do some cleanup and testing later.

**Comment by Rivridis** [comment]
I noticed an issue, the entire PDF RAG prompt got replaced with a random custom prompt, thus breaking it., please fix that if you can.

**Comment by Rivridis** [comment]
I have created a dev branch so it will make the integration much easier

**Pull request merged**
